[package]
name = "jieba-rs"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
description = "The Jieba Chinese Word Segmentation Implemented in Rust"
keywords = ["nlp", "chinese", "segmenation"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/messense/jieba-rs"

[dependencies]
radix_trie = "0.1"
smallvec = "0.6"
regex = "1.0"
lazy_static = "1.0"
phf = "0.7"

[build-dependencies]
phf_codegen = "0.7"
