[package]
name = "jieba-capi"
version = "0.1.0"
authors = ["messense <messense@icloud.com>"]
edition = "2018"

[dependencies]
jieba-rs = { version = "0.4", path = "../" }

[lib]
crate-type = ["cdylib"]
